language: rust
rust: nightly

branches:
  only:
  - master

addons:
  apt:
    packages:
    - libxmu-dev

# CMake 2.8.11 or greater is required; update it manually.
before_install:
    - sudo add-apt-repository --yes ppa:kalakris/cmake
    - sudo apt-get update -qq
    - sudo apt-get install cmake
