[package]

name = "amp"
version = "0.0.1"
authors = ["Jordan MacDonald <jordan@wastedintelligence.com>"]

[dependencies]
scribe = "0.3.1"
pad = "0.1.4"
rustbox = "0.6.1"
luthor = "0.1.1"
bloodhound = "0.1.1"

[dependencies.clipboard]
git = "https://github.com/aweinstock314/rust-clipboard.git"
