[package]

name = "amp"
version = "0.0.1"
authors = ["Jordan MacDonald <jordan@wastedintelligence.com>"]

[dependencies]
scribe = "0.4.4"
pad = "0.1.4"
rustbox = "0.7.2"
bloodhound = "0.2.3"
luthor = "0.1.7"
git2 = "0.3.3"
fragment = "0.1.1"
regex = "0.1"

[dependencies.clipboard]
git = "https://github.com/aweinstock314/rust-clipboard.git"
