[package]

name = "amp"
version = "0.2.0"
authors = ["Jordan MacDonald <jordan@wastedintelligence.com>"]

[dependencies]
scribe = "0.5.4"
pad = "0.1.4"
bloodhound = "0.3.0"
luthor = "0.1.7"
git2 = "0.6"
fragment = "0.2.0"
regex = "^0.1"
libc = "0.2.4"
syntect = "1.0.4"
rustbox = "0.9.0"
termion = { git = "https://github.com/jmacdonald/termion", branch = "esc" }
error-chain = "0.7.1"
preferences = "1.1.0"
unicode-segmentation = "1.0.1"

[dependencies.clipboard]
git = "https://github.com/aweinstock314/rust-clipboard.git"
