[package]

name = "amp"
version = "0.0.1"
authors = ["Jordan MacDonald <jordan@wastedintelligence.com>"]

[dependencies]
scribe = "0.4.3"
pad = "0.1.4"
rustbox = "0.7.2"
bloodhound = "0.2.1"
luthor = "0.1.7"

[dependencies.clipboard]
git = "https://github.com/aweinstock314/rust-clipboard.git"
