[package]

name = "amp"
version = "0.0.1"
authors = ["Jordan MacDonald <jordan@wastedintelligence.com>"]

[dependencies]
scribe = "0.4.10"
pad = "0.1.4"
bloodhound = "0.2.4"
luthor = "0.1.7"
git2 = "0.3.3"
fragment = "0.1.2"
regex = "^0.1"
libc = "0.2.4"
syntect = "1.0.0"
rustbox = "0.9.0"
termion = { git = "https://github.com/jmacdonald/termion", branch = "esc" }

[dependencies.clipboard]
git = "https://github.com/aweinstock314/rust-clipboard.git"
