[package]

name = "amp"
version = "0.0.1"
authors = ["Jordan MacDonald <jordan@wastedintelligence.com>"]

[dependencies]
scribe = "0.2.0"
pad = "0.1.4"
rustbox = "0.6.1"
luthor = "0.1.1"
bloodhound = "0.0.1"
