site_name: Amp
docs_dir: 'pages'
theme:
  logo: 'images/logo.svg'
  name: 'material'
repo_name: 'jmacdonald/amp'
repo_url: 'https://github.com/jmacdonald/amp'
pages:
  - 'index.md'
  - 'installation.md'
  - 'usage.md'
  - 'configuration.md'
extra:
  palette:
    primary: 'blue grey'
    accent: 'red'
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
extra_css:
  - 'stylesheets/extra.css'
