site_name: Amp
docs_dir: 'pages'
theme_dir: 'themes/mkdocs-material/material'
repo_name: 'jmacdonald/amp'
repo_url: 'https://github.com/jmacdonald/amp'
pages:
  - 'index.md'
  - 'preferences.md'
extra:
  palette:
    primary: 'blue grey'
    accent: 'red'
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
